[package]
name = "iui"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "examples/*"
]

[dependencies]
log = "0.4.17"
pretty_env_logger = "0.4.0"
soulscaper = { git = "https://github.com/PORTALSURFER/soulscaper" }
thiserror = "1.0.40"
winit = "0.28.3"
